def tool_send_report(summary: str, recipient_email: str, trace_id: str) -> dict: 
    import smtplib 
    from email.mime.text import MIMEText 
    from datetime import datetime 
    import os 
    
    subject = f"AI Agent Report - {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC" 
    body = f"Summary:\n{summary}\n\nGenerated by AI Workflow Agent\nTrace ID: {trace_id}" 
    
    msg = MIMEText(body) 
    msg["Subject"] = subject 
    msg["From"] = os.getenv("SMTP_USER") 
    msg["To"] = recipient_email 
    
    try:
        with smtplib.SMTP(os.getenv("SMTP_HOST"), int(os.getenv("SMTP_PORT", 587))) as server: 
            server.starttls() 
            server.login(os.getenv("SMTP_USER"), os.getenv("SMTP_PASS")) 
            server.send_message(msg) 
        return {"sent": True, "recipient": recipient_email, "subject": subject} 
    except Exception as e:
        return {"sent": False, "error": str(e), "recipient": recipient_email}
