apiVersion: v1
kind: Secret
metadata:
  name: ai-agent-secrets
type: Opaque
data:
  # Values must be base64 encoded
  # echo -n "value" | base64
  JWT_SECRET: WTNWaVpYSnpaV055WlhRZ2RYTmxiV1Z1ZEhScG93PT0= # example
  ENCRYPTION_KEY: TFBUa3pZQW5aZ0xCdFhwNjdqQ2QtWVZWay1yM2c3cEdaVWJzUFhIR1JwND0= # example
  OPENAI_API_KEY: c2st...
  SMTP_PASS: cGFzc3dvcmQ=
  GOOGLE_CLIENT_SECRET: c2VjcmV0
